### ISSUE TITLE
May I help You?

### ISSUE THREAD

**Issue by hind-sagar-biswas** [jovialcore/portfo#1]
Hello, I'm a full stack developer. I've currently nothing to do although currently building a web app. Yet I'm bored.. I'd like to help you if I can``

**Comment by jovialcore** [comment]
Oh thanks so much for contact me. I appreciate the help...I currently will not be needing assistance for now. May be in future.. Thak you so much

**Comment by hind-sagar-biswas** [comment]
Ok. @jovialcore thanks for your response.
